[2025-09-03T19:37:44.337+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: streaming_complete_pipeline.create_kafka_topic scheduled__2023-12-31T00:00:00+00:00 [queued]>
[2025-09-03T19:37:44.343+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: streaming_complete_pipeline.create_kafka_topic scheduled__2023-12-31T00:00:00+00:00 [queued]>
[2025-09-03T19:37:44.343+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T19:37:44.343+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-09-03T19:37:44.343+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T19:37:44.350+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): create_kafka_topic> on 2023-12-31 00:00:00+00:00
[2025-09-03T19:37:44.353+0000] {standard_task_runner.py:55} INFO - Started process 263 to run task
[2025-09-03T19:37:44.354+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'streaming_complete_pipeline', 'create_kafka_topic', 'scheduled__2023-12-31T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag_streaming_complete.py', '--cfg-path', '/tmp/tmpkec8h3us']
[2025-09-03T19:37:44.356+0000] {standard_task_runner.py:83} INFO - Job 2: Subtask create_kafka_topic
[2025-09-03T19:37:44.366+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T19:37:44.383+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T19:37:44.401+0000] {task_command.py:388} INFO - Running <TaskInstance: streaming_complete_pipeline.create_kafka_topic scheduled__2023-12-31T00:00:00+00:00 [running]> on host e954bc4828da
[2025-09-03T19:37:44.453+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Klaus_Rezende
AIRFLOW_CTX_DAG_ID=streaming_complete_pipeline
AIRFLOW_CTX_TASK_ID=create_kafka_topic
AIRFLOW_CTX_EXECUTION_DATE=2023-12-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-31T00:00:00+00:00
[2025-09-03T19:37:44.454+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-09-03T19:37:44.454+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec kafka kafka-topics --create --topic streaming_data --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 --if-not-exists']
[2025-09-03T19:37:44.460+0000] {subprocess.py:86} INFO - Output:
[2025-09-03T19:37:44.464+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: docker: command not found
[2025-09-03T19:37:44.464+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-09-03T19:37:44.471+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-09-03T19:37:44.473+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=streaming_complete_pipeline, task_id=create_kafka_topic, execution_date=20231231T000000, start_date=20250903T193744, end_date=20250903T193744
[2025-09-03T19:37:44.480+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 2 for task create_kafka_topic (Bash command failed. The command returned a non-zero exit code 127.; 263)
[2025-09-03T19:37:44.486+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-09-03T19:37:44.501+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
